const STATUS = {
	IDLE: 'idle',
	MOVING_UP: 'moving UP',
	MOVING_DOWN: 'moving DOWN',
	READY: 'READY',
	STARTED: 'STARTED',
	FINISHED: 'FINISHED',
	ONGOING: 'ONGOING',
	PENDING: 'PENDING',
};

export { STATUS };
